# Generated by Django 5.1.1 on 2024-10-09 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=225, null=True, unique=True, verbose_name='Username'),
        ),
    ]
