from django.urls import path
from rest_framework.routers import DefaultRouter
from bookmarker.api.json_views import (
    UserBookmarksList,
    UserBookmarksListNoPagination,
    UserBookmarkDetailView,
    BookmarkMultipleDeleteUsingPost,
    UserBookmarksCSVImport,
    BookmarkViewSet,
    get_categories_with_link,
    GetBookmarksByCategory,
    GetBookmarksWithCategory
)
from bookmarker.api.html_views import (
    BookmarkerIndexView,
    BookmarksListView
)
from bookmarker.views.views import (
    BookmarkerRootAPIView
)

app_name = 'bookmarker'
urlpatterns = [
    # json
    path('api/bookmarks-with-category/', GetBookmarksWithCategory.as_view(), name='bookmarks_with_category'),
    path('api/bookmarks-by-category/', GetBookmarksByCategory.as_view(), name='bookmarks_by_category'),
    path('api/category-list', get_categories_with_link, name='categories_list'), 
    path('api/file-upload/', UserBookmarksCSVImport.as_view(), name='file_upload'),
    path('api/multiple-delete/', BookmarkMultipleDeleteUsingPost.as_view(), name='multiple_delete'),
    path('api/<int:pk>/', UserBookmarkDetailView.as_view(), name='item'),
    path('api/no-paginate/', UserBookmarksListNoPagination.as_view(), name='list_no_pagination'),
    path('api/', UserBookmarksList.as_view(), name='list'),

    # html
    path('html/index/', BookmarkerIndexView.as_view(), name='html_index'),
    path('html/list/', BookmarksListView.as_view(), name='html_list'),
    
    # root
    path('', BookmarkerRootAPIView.as_view(), name='index'),
]

bookmarks_json_router = DefaultRouter()
bookmarks_json_router.register(r'bookmarks', BookmarkViewSet, basename='bookmarks')
# url generated by router: bookmarker/bookmarks

urlpatterns += bookmarks_json_router.urls