# Generated by Django 5.1.1 on 2024-09-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarker', '0002_alter_bookmark_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='title',
            field=models.CharField(max_length=120, verbose_name='Title'),
        ),
    ]
